services:
  ssl-certbot:
    build: . ${DOCKER_REG_ORG}/${DOCKER_IMG_NAME}:${DOCKER_IMG_TAG:-latest}
    image: ${DOCKER_REG_ORG}/${DOCKER_IMG_NAME}:${DOCKER_IMG_TAG:-latest}
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ssl_data:/etc/letsencrypt
    tmpfs:
      - /var/lib/letsencrypt

volumes:
  ssl_data:
    name: ssl_data
    driver: local
    