services:
  ssl-certbot:
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: ${DOCKER_REG_ORG}/${CERTBOT_IMG_NAME}:${CERTBOT_IMG_TAG:-latest}
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ssl_data:/etc/letsencrypt
    tmpfs:
      - /var/lib/letsencrypt
    restart: always

volumes:
  ssl_data:
    name: ssl_data
    driver: local