name: Certbot CI/CD

on:
  push:
    branches:
      - main    # 운영
      - release # 스테이징
      - develop # 개발

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # 환경별 변수 적용 (prod, stage, dev)
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'release' && 'stage' || github.ref_name == 'develop' && 'dev' }}
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v5
      - name: 도커 허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 이미지 빌드하고 푸시하기
        run: |
          docker build --platform linux/amd64 -t ${{ vars.DOCKER_REG_ORG }}/${{ vars.CERTBOT_IMG_NAME }}:${{ vars.CERTBOT_IMG_TAG }} .
          docker push ${{ vars.DOCKER_REG_ORG }}/${{ vars.CERTBOT_IMG_NAME }}:${{ vars.CERTBOT_IMG_TAG }}

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'release' && 'stage' || github.ref_name == 'develop' && 'dev' }}
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v5
      
      - name: SSH 키 준비하기
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2-ssh-private-key.pem
          chmod 600 ~/.ssh/ec2-ssh-private-key.pem
          ssh-keyscan -H ${{ secrets.EC2_SERVER_HOST }} >> ~/.ssh/known_hosts

      # 1. .env 파일 생성
      - name: 환경변수 파일(.env) 만들기
        run: |
          cat <<EOF > .env
          # 이미지 정보
          DOCKER_REG_ORG=${{ vars.DOCKER_REG_ORG }}
          CERTBOT_IMG_NAME=${{ vars.CERTBOT_IMG_NAME }}
          CERTBOT_IMG_TAG=${{ vars.CERTBOT_IMG_TAG }}
          
          # SSL 설정
          DOMAIN=${{ vars.DOMAIN }}
          EMAIL=${{ vars.EMAIL }}
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          EOF

      # 2. 파일 서버로 전송 (.env + docker-compose.yml)
      - name: 배포 파일들 EC2로 보내기
        run: |
          ssh -i ~/.ssh/ec2-ssh-private-key.pem ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} "mkdir -p /home/${{ vars.EC2_SERVER_USER }}/app/certbot"
          scp -i ~/.ssh/ec2-ssh-private-key.pem docker-compose.yml .env ${{ vars.EC2_SERVER_USER  }}@${{ secrets.EC2_SERVER_HOST }}:/home/${{ vars.EC2_SERVER_USER }}/app/certbot/

      - name: 도커 설치되어 있나 확인
        id: check-docker
        run: |
          DOCKER_EXISTS=$(ssh -i ~/.ssh/ec2-ssh-private-key.pem -o StrictHostKeyChecking=no ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} 'command -v docker >/dev/null && echo "true" || echo "false"')
          echo "docker_exists=$DOCKER_EXISTS" >> $GITHUB_OUTPUT

      - name: 도커 없으면 설치하기
        if: steps.check-docker.outputs.docker_exists == 'false'
        run: |
          ssh -i ~/.ssh/ec2-ssh-private-key.pem -o StrictHostKeyChecking=no ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} << 'EOF'
              sudo apt-get update
              sudo apt-get install -y \
                  ca-certificates \
                  curl \
                  gnupg \
                  lsb-release
              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
                | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
                https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" \
                | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
              sudo usermod -aG docker $USER
          EOF

      # 3. 배포 실행
      - name: 도커 컴포즈로 배포 시작
        run: |
          ssh -i ~/.ssh/ec2-ssh-private-key.pem -o StrictHostKeyChecking=no ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} << EOF
              cd ~/app/certbot
              docker compose down
              docker compose pull
              docker compose up -d
              docker image prune -f
          EOF

# [설정 가이드]
# 깃헙 레포 Settings > Secrets and variables > Actions 에 등록
#
# 1. Secrets
# - DOCKER_TOKEN, EC2_SSH_PRIVATE_KEY
# - EC2_SERVER_HOST
# - CLOUDFLARE_API_TOKEN
#
# 2. Variables
# - DOCKER_USER_NAME, DOCKER_REG_ORG
# - CERTBOT_IMG_NAME, CERTBOT_IMG_TAG
# - DOMAIN, EMAIL
# - EC2_SERVER_USER
